name: Test

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Update release tag
        run: |
          git tag -d test
          git push origin :refs/tags/test
          git tag test
          git push origin refs/tags/test

      - name: Run
        uses: ./
        with:
          tag_name: test
          recreate_release: always